apiVersion: apps/v1
kind: Deployment
metadata:
  name: pydb
  labels:
    app: pydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pydb
  template:
    metadata:
      labels:
        app: pydb
    spec:
      containers:
        - image: mysql:5.6
          name: pydb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rootpass
                  key: rootpass
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pass
                  key: pass
          ports:
            - containerPort: 3306
              name: pydb
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim
